# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_garmentproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricstockinfo',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabricstockinfo',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
