# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160106_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentproduction',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Fabric'),
        ),
    ]
